Jessica cooper
JessicaGCooper/UI-III-Flexbox pull request #1
Opened 2019-09-04 23:22 UTC by JessicaGCooper

Unfinished.

2019-09-05 20:43 UTC, evan-leduc requested changes
Looks great, just could use a couple of adjustments.

2019-09-05 20:43 UTC, Eiosx commented on great-idea/services.html
> +    <img class="services-header-img" src="img/services-header.jpg" alt="Our services header image"/>
Page looks good, just need to change a couple of things. Add some margin on top of the img to space it from the header.

2019-09-05 20:43 UTC, Eiosx commented on great-idea/services.html
> +      <nav>
Minute detail, but try shortening the space between the nav and the great idea img.

2019-09-05 20:43 UTC, Eiosx commented on great-idea/services.html
> +        <button>Learn More</button>
Try changing the background-color for each button to a white-like color.

2019-09-05 22:22 UTC, JessicaGCooper commented on great-idea/services.html
> +      <nav>
It seems this was in part because the "about" Nav item was missing.  Tricky.

2019-09-05 22:22 UTC, JessicaGCooper commented on great-idea/services.html
> +    <img class="services-header-img" src="img/services-header.jpg" alt="Our services header image"/>
Got it!

2019-09-05 22:23 UTC, JessicaGCooper commented on great-idea/services.html
> +        <button>Learn More</button>
Is it too white?

2019-09-06 04:22 UTC, evan-leduc approved these changes
Great job on the changes, looks even better!

2019-09-06 04:22 UTC, merged